### ISSUE TITLE
JRuby support

### ISSUE THREAD

**Issue by brauliobo** [hanami/api#18]
Hi, I currently see Hanami API depends on Ruby 2.7.0, are there plans to support JRuby?

**Comment by jodosha** [comment]
@brauliobo I'm planning to back port the support to MRI 2.6, when JRuby will reach [9.3.0.0](https://github.com/jruby/jruby/milestone/69) it will be compatible with this gem.

I don't plan to support MRI 2.5 (and so JRuby 9.2.0.0), because MRI 2.5 will reach EOL in [6 months](https://www.ruby-lang.org/en/downloads/branches/).
