### ISSUE TITLE
Example project with hanami API.

### ISSUE THREAD

**Issue by serjpetrenko** [hanami/api#4]
Is it possible to see an example of how to use it, some example application?

**Comment by cllns** [comment]
Have you looked at the examples in the README?

This [`config.ru`](https://github.com/hanami/api#usage) is an example of how it works. Throw that into a folder with `gem 'hanami-api'` in a Gemfile, run `bundle install` then `bundle exec rackup`, hit localhost:9292/ and you'll see `Hello, world` in plaintext. 

This library is really quite minimal, I think you should start with the above then play with the other options listed in the README. 
Alternately, you could look at this app that's used in the specs: https://github.com/hanami/api/blob/master/spec/integration/hanami/api/block_spec.rb#L7-L129

If that's not enough, could you be more specific about what you'd like to see?

**Comment by ilasorsa** [comment]
@cllns without specifying the version `0.0.0` is used and I got this trying the minimal example

`uninitialized constant Hanami::API (NameError)
Did you mean?  Hanami::Api`

This did the trick

gem "hanami-api", "0.1.0"

**Comment by serjpetrenko** [comment]
@cllns Thanks for your comment. Yes, I read the whole readme file and I saw an example that you are described. But with my question, I mean next - a real project that uses `gem 'hanami-api'`. Is it possible to use it with the `gem 'hanami-model'`?

**Comment by cllns** [comment]
> @cllns without specifying the version `0.0.0` is used and I got this trying the minimal example
> 
> ```
> uninitialized constant Hanami::API (NameError)
> Did you mean?  Hanami::Api
> ```
> 
> This did the trick
> 
> ```
> gem "hanami-api", "0.1.0"
> ```

Ah, I see. It looks like `0.0.0` was just @jodosha saving the name for the future. I think you probably got it because `0.1.0` only supports Ruby 2.7+. When I was using 2.7, I got `0.1.0` without specifying the version number. 

@jodosha What do you think about yanking `0.0.0` from Rubygems.org, since it's not useful anymore?

**Comment by cllns** [comment]
> @cllns Thanks for your comment. Yes, I read the whole readme file and I saw an example that you are described. But with my question, I mean next - a real project that uses `gem 'hanami-api'`. Is it possible to use it with the `gem 'hanami-model'`?

Yup, can definitely use it with `hanami-model`. Or `rom`. Even `activerecord` if you wanted to :) This is a very minimal library, it makes no assumptions about any other layer of the application. It's basically a thin layer on top of `hanami-model` (version 2).

You can see `hanami-model` being used here: https://github.com/hanami/api#json with `UserRepository` possibly being from `hanami-model`. It could be from anywhere though, this library doesn't care. It just cares about getting a Ruby object (in this case, using the `json(...)` method, a JSON serializeable object, to be specific).

This library is really so minimal that any full application example would be illustrating more about the problem domain rather than anything else. I think the README might be the best way to illustrate exactly what this library does.

**Comment by serjpetrenko** [comment]
@cllns Thanks for comments ;)
