### ISSUE TITLE
Can't understand the usage of POST method

### ISSUE THREAD

**Issue by alexanderkustov** [hanami/api#7]
I have made the simplest App in the world to test this out.

```ruby
 # frozen_string_literal: true

require "bundler/setup"
require "hanami/api"

class App < Hanami::API
  post "/simplePost" do
    puts params
    puts status, headers, body
    puts params[:foobar]
    json( params[:foobar] )
  end
end
```

So as i go into my postman, or any other way of getting a curl there.
`curl --data "foobar=value1" http://localhost:9292/simplePost --header "Content-Type:application/json"`

This is what I get:

```
 {}
200
{}
```

Is there another way of passing, getting params here?

**Comment by cllns** [comment]
Hey sorry you ran into this problem. It's not clear what's happening here, but the problem is that `hanami-router` doesn't include a body parser by default. That's why using `params` (which accesses `env['router.params']`) works for GET , since those params come from the URL, but not POST or PUT/PATCH body. See: https://github.com/hanami/router/tree/v2.0.0.alpha2#body-parsers

If you add `require "hanami/middleware/body_parser"` to the top of your file, and `use Hanami::Middleware::BodyParser, :json`, you'll be able to parse JSON bodies. But you still won't be able to parse URL encoded bodies, like the one you provided, so your `curl` arg will need to be `--data '{"foobar":"value1"}'`. You can write a custom body parser too, though.

I'm not sure what the right solution is here. Obviously documenting this would be a first-step, but I wonder if `hanami-api` should Just Work with JSON bodies (likely my vote). Or, we should at least display something to the developer saying they need to include a body parser.

**Comment by alexanderkustov** [comment]
Thank you for your reply, I am happy to document this if needed and put into a readme, or wiki of the project, because otherwise it's easy to get params into the GET but as soon as anyone wants to develop a bit more he will run into this.

**Comment by cllns** [comment]
I'm wondering if we shouldn't handle this in code. Here are some options:
1. create a `Hanami::API::JSON` class that automatically adds the JSON body parser middleware to the stack. And keep the existing class for people who don't need a body parser, or want to use their own.
2. check to see if there is any body parser in the middleware yet, and if there's not, add the JSON one (it might be hard to see what the middleware does though, since it doesn't have to have a `Hanami::Middleware` namespace)
3. add some syntax like `self.body_parser = :json` to the `API` class which automatically adds the body parser middleware.

**Comment by jodosha** [comment]
@alexanderkustov Your "issue" is fair common, but full fledged frameworks like Hanami or Rails always put in place a mechanism to merge POST body into `params` for convenience sake.

Being Hanami::API stripped down in functionalities, you should do:

```ruby
require "hanami/api"
require "hanami/middleware/body_parser"

class MyApi < Hanami::API
  use Hanami::Middleware::BodyParser, :json

  # ...
end
```

I believe that this should be documented in `README`. @alexanderkustov can you please take care of this? Thanks in advance.

**Comment by jodosha** [comment]
@cllns 

For the sake of simplicity (and perf), I'd keep things as they are because:

> 1. create a Hanami::API::JSON class that automatically adds the JSON body parser middleware to the stack. And keep the existing class for people who don't need a body parser, or want to use their own.

Body parsers can support multiple formats other than JSON, having a separated superclass just for this makes things harder to explain.

> 2. check to see if there is any body parser in the middleware yet, and if there's not, add the JSON one (it might be hard to see what the middleware does though, since it doesn't have to have a Hanami::Middleware namespace)

We shouldn't assume that all the APIs are for JSON. GraphQL or text based APIs won't need a body parser. Adding it, will add unnecessary perf overhead where not required. Better to let people to opt-in.

> 3. add some syntax like self.body_parser = :json to the API class which automatically adds the body parser middleware.

That would complicate the internal design. If people need the body parser, they can reach documentation (as they would do to learn about `self.body_parser = :json`) and they will discover a different syntax, which costs them 2 lines of code (`require` and `use`). It isn't a big deal, as long as it is documented.

**Comment by cllns** [comment]
:+1:
